### ISSUE TITLE
Some small feedback

### ISSUE THREAD

**Issue by remlapmot** [chr1swallace/coloc#27]
Hi Chris,

I did a quick scan. Hopefully the following is helpful.

* `DESCRIPTION`: (I am not 100% sure if the following is needed or not) Perhaps you are missing a line specifying that **snpStats** comes from Bioconductor, i.e.
    ```
    Remotes: bioc::release/snpStats
    ```

* `DESCRIPTION`: You could include the ORCiDs of yourself and your co-authors in the `Authors@R` vector. You add this to each person in a with the `comment` option, e.g. `comment = c(ORCID = "XXXX-XXXX-XXXX-XXXX")`.

* `_pkdown.yaml`: Currently your pkgdown/githubpages site is missing the rendered vignettes, i.e. the [Articles](https://chr1swallace.github.io/coloc/articles/index.html) page is blank. I think this is because your code in `_pkgdown.yaml` is too complicated. I think you are trying to exclude `simdata.Rmd` from being shown as a separate vignette so I would code: 
    ```
    articles:
    - title: Vignettes
      navbar: ~
      contents:
      - a01_intro
      - a02_proportionality
      - a03_enumeration
      - a04_sensitivity
      - a05_conditioning
    ```
    And from `simdata.Rmd` remove the `vignette:` section in its header.

* `README.md`: 
  * To build the vignettes is the code before `devtools::build_vignettes()` necessary?
  * The RStudio folk usually put their build badges just below the title of the `README`.

* GitHub repo: This is missing the link to your githubpages URL in the standard place, i.e. add the githubpages URL in your repo settings

Best wishes
  Tom
